---
- hosts: all

  pre_tasks:

    - name: Create Installs directories
      file: path=~/Installs state=directory

    - name: Symlink ~/Installs
      file: src=~/Installs dest=/tmp/Installs state=link

    - name: Install apt-transport-https
      apt: pkg=apt-transport-https
      become: yes

    - name: Install pip
      apt: pkg=python-pip
      become: yes

  roles:
    - source-control
    - vim
    - system
    - monitoring
    - configuration-management
    - internet
    - media
    - clojure
