---
- hosts: all

  pre_tasks:

    - name: Make sure kali repository is disabled
      apt_repository: repo="deb http://http.kali.org/kali kali-rolling main contrib non-free" state=absent update_cache=yes
      become: yes

    - name: Install SSH server
      apt: pkg=openssh-server
      become: yes

    - name: Install sshpass
      apt: pkg=sshpass
      become: yes

    - name: Disable SSHD startup
      shell: update-rc.d ssh disable
      become: yes

    - name: Create Installs directories
      file: path=~/Installs state=directory

    - name: Symlink ~/Installs
      file: src=~/Installs dest=/tmp/Installs state=link

    - name: Install apt-transport-https
      apt: pkg=apt-transport-https
      become: yes

    - name: Install pip
      apt: pkg=python-pip
      become: yes

    - name: Install unzip
      apt: pkg=unzip
      become: yes

  roles:
    - source-control
    - vim
    - system
    - security
    - monitoring
    - configuration-management
    - media
    - clojure
    - nodejs
    - ruby
    - internet
    - office
