- name: Install tor anonymizing overlay network for TCP
  apt: pkg=tor
  become: yes

- name: Disable tor startup
  shell: update-rc.d tor disable
  become: yes

- name: Install nmap for network discovery and security auditing
  apt: pkg=nmap
  become: yes

- name: Add kali apt key
  apt_key: keyserver=pgp.mit.edu id=ED444FF07D8D0BF6
  become: yes

- name: Add kali repository
  apt_repository: repo="deb http://http.kali.org/kali kali-rolling main contrib non-free"
  become: yes

- name: Install dnsmap
  apt: pkg=dnsmap
  become: yes
