- name: Install tor anonymizing overlay network for TCP
  apt: pkg=tor
  become: yes

- name: Disable tor startup
  shell: update-rc.d tor disable
  become: yes

- name: Install nmap for network discovery and security auditing
  apt: pkg=nmap
  become: yes

- name: Add kali apt key
  apt_key: keyserver=pgp.mit.edu id=ED444FF07D8D0BF6
  become: yes

- name: Add kali repository
  apt_repository: repo="deb http://http.kali.org/kali kali-rolling main contrib non-free"
  become: yes

- name: Install dnsmap for brute force DNS name discovery
  apt: pkg=dnsmap update_cache=yes
  become: yes

- name: Install ncrack network authentication cracking tool
  apt: pkg=ncrack
  become: yes

- name: Install skipfish web application security reconnaissance tool
  apt: pkg=skipfish
  become: yes

- name: Install grabber web application scanner
  apt: pkg=grabber
  become: yes

- name: Install XSSer to detect, exploit and report on XSS vulnerabilities
  apt: pkg=xsser
  become: yes

- name: Install rainbowcrack
  apt: pkg=rainbowcrack
  become: yes

- name: Install theHarvester e-mail account and subdomain discovery tool
  apt: pkg=theharvester
  become: yes

- name: Install hping3 network smashing tool
  apt: pkg=hping3
  become: yes

- name: Install slowhttptest network smashing tool
  apt: pkg=slowhttptest
  become: yes

- name: Install netstress network activity benchmarking tool
  apt: pkg=netstress
  become: yes

- name: Install ApacheBench
  apt: pkg=apache2-utils
  become: yes

- name: Install siege HTTP/HTTPS stress tester
  apt: pkg=siege
  become: yes

- name: Install mitmproxy for interactive examination and modification of HTTP traffic
  apt: pkg=mitmproxy
  become: yes
