- name: Install gnote note taking application
  apt: pkg=gnote
  become: yes

- name: Install TaskWarrior To-Do
  apt: pkg=taskwarrior
  become: yes

- name: Install dbeaver database manager/client
  apt: pkg=dbeaver
  become: yes
