- name: Install gnote note taking application
  apt: pkg=gnote
  become: yes

- name: Install TaskWarrior To-Do
  apt: pkg=taskwarrior
  become: yes

- name: Install TaskWarrior terminal interface
  apt: pkg=vit
  become: yes

- name: Install PlantUML diagramming tool
  apt: pkg=plantuml
  become: yes

- name: Install cloc for counting lines of code
  apt: pkg=cloc
  become: yes

- name: Install Electron Packager
  npm: name=electron-packager version=13.0.1 global=yes
  become: yes
