- name: Install lshw for listing hardware details
  apt: pkg=lshw
  become: yes

- name: Install wicd for network management
  apt: pkg=wicd-gtk
  become: yes

- name: Remove gnome default network management
  apt: pkg={{ item }} state=absent
  with_items:
  - network-manager-gnome
  - network-manager
  become: yes

- name: Install terminator terminal emulator
  apt: pkg=terminator
  become: yes

- name: Create terminator configuration directory
  file: path=~/.config/terminator state=directory

- name: Copy terminator configuration
  copy: src=terminator.config dest=~/.config/terminator/config

- name: Install tmux terminal multiplexer
  apt: pkg=tmux
  become: yes

- name: Install Midnight Commander file manager
  apt: pkg=mc
  become: yes

- name: Install i3 windows manager
  apt: pkg={{ item }}
  with_items:
  - i3
  - suckless-tools
  become: yes

- name: Install curl
  apt: pkg=curl
  become: yes

- name: Install avahi
  apt: pkg=avahi-daemon
  become: yes

- name: Install whois
  apt: pkg=whois
  become: yes

- name: Install HTTPie cURL wrapper
  apt: pkg=httpie
  become: yes

- name: Install lynx command line browser
  apt: pkg=lynx
  become: yes

- name: Install NCurses Disk Usage utility
  apt: pkg=ncdu
  become: yes

- name: Install wondershaper for limiting adapter bandwidth
  apt: pkg=wondershaper
  become: yes

- name: Install Kupfer launcher
  apt: pkg=kupfer
  become: yes

- name: Install apt file
  apt: pkg=apt-file
  become: yes

- name: Install locate
  apt: pkg=mlocate
  become: yes

- name: Install icdiff side by side diff tool
  apt: pkg=icdiff
  become: yes

- name: Add non-free repository to provide DropBox
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^deb http:\/\/.*stretch main'
    line: 'deb http://ftp.iinet.net.au/debian/debian/ stretch main non-free'
  become: yes

- name: Install DropBox
  apt: pkg=nautilus-dropbox update_cache=yes
  become: yes

- name: Disable non-free repository to provide DropBox
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^deb http:\/\/.*stretch main non-free'
    line: 'deb http://ftp.iinet.net.au/debian/debian/ stretch main'
  become: yes

- name: Update apt cache
  apt: update_cache=yes
  become: yes
