- name: Install lshw for listing hardware details
  apt: pkg=lshw
  become: yes

- name: Install wicd for network management
  apt: pkg=wicd-gtk
  become: yes

- name: Remove gnome default network management
  apt: pkg={{ item }} state=absent
  with_items:
  - network-manager-gnome
  - network-manager
  become: yes

- name: Install terminator terminal emulator
  apt: pkg=terminator
  become: yes

- name: Create terminator configuration directory
  file: path=~/.config/terminator state=directory

- name: Copy terminator configuration
  copy: src=terminator.config dest=~/.config/terminator/config

- name: Install tmux terminal multiplexer
  apt: pkg=tmux
  become: yes

- name: Install Midnight Commander file manager
  apt: pkg=mc
  become: yes

- name: Install i3 windows manager
  apt: pkg={{ item }}
  with_items:
  - i3
  - suckless-tools
  become: yes

- name: Install curl
  apt: pkg=curl
  become: yes

- name: Install avahi
  apt: pkg=avahi-daemon
  become: yes

- name: Install whois
  apt: pkg=whois
  become: yes

- name: Install HTTPie cURL wrapper
  apt: pkg=httpie
  become: yes

- name: Install lynx command line browser
  apt: pkg=lynx
  become: yes

- name: Install NCurses Disk Usage utility
  apt: pkg=ncdu
  become: yes

- name: Install wondershaper for limiting adapter bandwidth
  apt: pkg=wondershaper
  become: yes

- name: Install Synapse launcher
  apt: pkg=synapse
  become: yes

- name: Install apt file
  apt: pkg=apt-file
  become: yes

- name: Install locate
  apt: pkg=mlocate
  become: yes

- name: Install icdiff side by side diff tool
  apt: pkg=icdiff
  become: yes
