- name: Install ansible
  apt: pkg=ansible
  become: yes

- name: Add VirtualBox repository key
  apt_key: url=https://www.virtualbox.org/download/{{ item }}.asc
  with_items:
  - oracle_vbox_2016
  become: yes

- name: Add VirtualBox repository
  apt_repository: repo='deb https://download.virtualbox.org/virtualbox/debian stretch contrib' update_cache=yes
  become: yes

- name: Install VirtualBox
  apt: pkg=virtualbox-5.2
  become: yes

- name: Install vagrant
  apt: pkg=vagrant
  become: yes
