- name: Install VLC media player
  apt: pkg=vlc
  become: yes

- name: Add spotify apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
  become: yes

- name: Add spotify repository
  apt_repository: repo="deb http://repository.spotify.com stable non-free"
  become: yes

- name: Install spotify client
  apt: pkg=spotify-client update_cache=yes
  become: yes

- name: Install shutter screenshot tool
  apt: pkg=shutter
  become: yes

- name: Install GIMP photo editor
  apt: pkg=gimp
  become: yes

- name: Install handbrake video converter
  apt: pkg=handbrake
  become: yes

- name: Download Auryo .deb
  get_url: url=https://github.com/Superjo149/auryo/releases/download/v1.4.3/Auryo_1.4.3_amd64.deb dest=~/Installs/Auryo_1.4.3_amd64.deb
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Auryo
  apt: deb=/tmp/Installs/Auryo_1.4.3_amd64.deb
  become: yes

- name: Install spotify downloader
  pip: name=spotdl executable=pip3
  become: yes
